build:  
  image: python:3.4
  commands:
    - echo "DATABASE_URL = 'postgis://postgres:postgres@db:5432/postgres'" > project/config/settings.py
    - pip install -r requirements.txt
    - python manage.py test --settings=project.settings_test
