build:  
  image: python:3.4
  commands:
    - echo "DATABASE_URL = 'postgis://postgres:postgres@127.0.0.1:5432/postgres'" > project/config/settings.py
    - pip install -r requirements.txt
    - python manage.py test --settings=project.settings_test
compose:	
  db:
    image: mdillon/postgis
    environment:
      - POSTGRES_PASWORD=postgres
notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'drone'
    channel: '#builds'
    on_started: false
    on_success: true
    on_failure: true
    template: |
      {{#success build.status}}
        {{ build.author }} is a bad ass coding gold on {{ build.link_url }} ({{ build.branch}}).
      {{else}}
        {{ build.author }} broke the build. Go to #the-taylor-swift-room please you naughty dev.
      {{/success}}