web:
  build: .
  command: /bin/bash --login -c "./manage.py collectstatic --noinput && ./manage.py migrate && uwsgi --http :8000 --wsgi-file project/wsgi.py --manage-script-name --static-map /static=/app/project/static;"
  labels:
    io.rancher.sidekicks: config
  ports:
    - 8000
  stdin_open: true
  volumes_from:
  - config

config:
  build: .config/prod
  command: cat
  labels:
    io.rancher.container.start_once: "true"
  read_only: true
  stdin_open: true
