web:
  command: /bin/bash --login -c "./manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  tty: true
  build: .
  volumes:
    - .:/app
  ports:
    - 8000:8000
  links:
    - db
db:
  image: mdillon/postgis
  environment:
    - POSTGRES_PASWORD=postgres