web:
  command: uwsgi --http :8000 --wsgi-file project/wsgi.py --static-map /static=/app/project/static
  build: .
  volumes:
    - .:/app
  links:
    - db
  ports:
    - "8000:8000"
  env_file:
    - .env
db:
  image: dangerfarms/postgis:latest
