# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='installed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
